\l 2003.09.10
S:100#>count't  / 100 top symbols

n:1
\t:n {select last b from q x}'S
\t:n {select max p by e from t x}'S
\t:n {select sum z by `h$t from t x}'S
\t:n a:select from(select t,p from t`QQQ;select t,b from q`QQQ)where p<b
#a
\

/ETL

\t t:select by s from +`s`t`e`c`z`p      !("ntccii"  ;",")0:"t.csv"
\t q:select by s from +`s`t`e`b`bz`a`az`m!("ntciiiic";",")0:"q.csv"
\t "2003.09.10"1:`t`q!(t;q)
\\
